name: Create release workflow

on: [workflow_dispatch]

jobs:
#  test:
#    name: Test - Units & Integrations
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v2
#      - name: Set up JDK 14
#        uses: actions/setup-java@v1
#        with:
#          java-version: 14
#      - name: Maven Package
#        run: mvn -B clean package -DskipTests
#      - name: Maven Verify
#        run: mvn -B clean verify
  
  create-release:
    name: Create release branch
    runs-on: ubuntu-latest
    needs: [test]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
          server-id: github
      - name: Configure Git user
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
      - name: Prepare
        id: prep
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout | sed 's/-SNAPSHOT//')
          echo ::set-output name=version::${VERSION}
      - name: Creat release branch
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'release/${{ steps.prep.outputs.version }}'
      - name: Update version
        run: |
          mvn -B release:update-versions 
          git commit -m "Aumentada la version" -a
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}